### ISSUE TITLE
Silver the early Magical Metal

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#11]
Silver needs to...

- [x]  Make Manasteel as per #1 
- [x]  Get used in the Occulus

anything else?

**Comment by belathus** [comment]
We could use silver instead of gold when making the mana spreader.

It could be a component in "magi-tech" type machines, like EnderIO's, though, that isn't exactly early game.

The sacrificial dagger (the 2nd tier one) from Blood Magic could be made from a silver sword instead of an iron one (assuming it still uses the old recipe; been a while since I messed with Blood Magic).

That's all I have for now.

**Comment by Divineaspect** [comment]
Howabout in addition to gold for the mana spreader.

the silver sword seems like a good idea, and now it's triggering more good ideas.

**Comment by belathus** [comment]
I'm thinking that soularium should be made with silver + soul sand rather than gold + soul sand.
