### ISSUE TITLE
Armor/Tool Breakdown

### ISSUE THREAD

**Issue by Lance5057** [belathus/Wanderlust-Renewed#121]
A way to melt/tear apart armor/tools into their respective materials would be nice.

**Comment by belathus** [comment]
I've been trying to think of how I'd do this. I mean, I could simply make it so fully repaired armor/tools can be melted down, but it'd be amazing if I could make it so that melting down a partially broken suit of armor returned an appropriate amount of fluid. I may be able to do this.

**Comment by Alan19** [comment]
Can you divide in minetweaker? If so, why not use a for loop to divide the total molten metal by the durability?

**Comment by belathus** [comment]
A part of the problem is that I'll need to use a function. I might be able to get away with it in the crafting grid, but I don't think any other recipe added by MineTweaker accepts a function in its output.

Does crafting pyrotheum dust with an ore still give you ingots? If so (or I could just use it anyway), maybe I can use this as the basis for melting down armor and tools.

**Comment by Divineaspect** [comment]
I think there are some recycling mods which do exactly this. Lemmie look around.
