### ISSUE TITLE
Neon and Alutine Sand in Deep Dark

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#42]

**Comment by belathus** [comment]
Neon is in there. I was thinking that, if I cannot remove the ability to turn alutine gems into aluminum, that we shouldn't allow alutine sand to be obtained, and instead make it so that alutine gems are made from aluminum somehow.

What I have in mind is perhaps putting molten aluminum in a gem cast creates alutine, or something like that.

**Comment by Divineaspect** [comment]
FP requires A LOT (read infinite) aluminum to make it's spaceships. Can we plan on making this content accessed with Advanced rocketry and shelve the issue until then?

**Comment by belathus** [comment]
Okay, I'll add alutine to Advanced Rocketry's asteroid or planet dimensions. I've already added neon to the ore generation in the Deep Dark in commit https://github.com/belathus/Wanderlust-Renewed/commit/57db05a09da564211b35698d4c563a448f0a5003.
