### ISSUE TITLE
The Wall and Gate of Bronze!

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#46]
The Stone age is an intended span of play, which you leave by getting access to bronze, which mines (once configed) at the bronze/iron level. (also putting iron ores at this level) So how to let people make  bronze?

Note that Grout due to #16  has only Alternate Recipes, requires mixtures of worldgen clays and manual processing.

Primal Core
    Smashing Tin and Copper Ores as a way to gain dust and mix them is something we could add.

Crack Hammer ?
     We'd disabled this approach as being too easy, as an entry point. But if we set Bronze to be it's first material, and disable it from cracking iron, it could make the Primal Core entry sustainable in the bronze age.

Smeltery
    This is kinda annoyingly the key to a lot of powerful tools. The alternate grout recipes took me an average of 3 hours to collect all the ingredients for them, but adding some other stone age material to the controller or bricks would be agreeable. I'm ok with (but not for) using some form of manually ground/mixed mortar to delay it/make it effectively early bronze age. 

Crucible (Esteemed Innovation)
    The EI Crucible can also be used to make alloys we want. Seared Bricks could/should be used for it's recipies to apply the logic of the delayed smeltery only less so. Maybe a Magma Creme or Mercury&Gold Amalgam to seal it's bricks together?

---

These are the solutions I can think of, open to both feedback on them and other ideas to make this gating work.

**Comment by Divineaspect** [comment]
@belathus Pointed out that theCrucible was pre-netherrack access. @satanicsanta showed the code works with both anything that  extends fire or lava. The lava pre buckets isn't really an issue.

**Comment by belathus** [comment]
In real life, both tin and copper required the addition of a flux (limestone) to remove the impurities. Tin, however, had the issue that you'd only recover about 10% of it each time you smelted it; the remaining 90% would drain with the slag, and require another pass to get more of it out, which made tin difficult to process. Fortunately, bronze only required a small amount of tin: 1 part tin to 8-9 parts copper.

Smashing the copper/tin ores with PrimalCore (via stone + stone basin + ore?) seems like a good approach for the first step. I think disabling the crack hammers prior to bronze might be also good. But, if we increase the cost of the furnace, how do we process the copper/tin mixture into ingots? The campfire? Crucible?

For the smeltery: I am considering removing the ability for it to process ores entirely; instead, it will only be able to melt down ingots, nuggets, and blocks (and other non-ore stuff). That way, it's primary use will be for making alloys and tool parts.

For the crucible: I'm more than happy to make this the easier-to-get method of making bronze than a smeltery.

**Comment by Divineaspect** [comment]
My ideas on the Furnace are

1. Hardened Mud, Bricks, netherbricks, seared bricks, or Terracotta on the corners.
2. An item on the center bottom representing mastery of fire. 
     a. Primal Core's magic fire thingie (add as a rare monster drop and/or quest reward), 
     b. Flint and Steel
     c. Fire Charge
     d. Dungeon Tactics Fire Flower (with reduced spawn frequency) in the center bottom.
     e. Magma as the post Nether easy option to avoid painful repetition. 
3. I like these, but I want it to not be grindy, and lets double check the campfire not cooking things.

**Comment by belathus** [comment]
Current furnace recipe: 3 stone brick blocks and 3 stone brick slabs. Do we still want something to represent the mastery of fire? Are we still interested in using the hardened mud, bricks, etc.? This is partially implemented with the dried clay bricks in the kiln.

Also, do we still want to allow players to grind tin, zinc, and copper ore to dust using the PrimalCore stone basin?

The crack hammer and crucible were removed. I'm hoping that the crucible will get re-added when Esteemed Innovation is fixed up.

**Comment by belathus** [comment]
Alright, lets talk about this one again.

The gate to bronze is the ability to make alloys. There are a few early ways to do that: the smeltery, the alloy kiln, and mixing dusts in a crafting grid.

The smeltery is barred behind tough grout recipes. We can make these tougher now that we have the ability to allow melting ores and metals via Tinker's Complement. I guess once we do that, I'll be a bit more comfortable with going back to ore doubling via the original smeltery as well (since Tinker's Complement allows us to set the ore return rate for that as well).

Porcelain's recipe is two clay plus one nether quartz to get 2 porcelain. We can potentially add certus quartz as a variant of nether quartz if we want to allow them access to porcelain before going to the nether or finding specific world gen.

The furnace recipe has been returned to the vanilla default of 8 cobblestone. @Divineaspect suggested a mastery of fire recipe for the furnace, and I'd be okay with going back to that. Additionally, we could require the dried clay bricks like we did before for the kiln. My thoughts on mastery of fire would be using primalcore's searing ember in the nether (the flaming grass; you simply cut it with shears then craft the sprig with a workblade to get the searing ember), the fire charge, the flaming flower, etc.

**Comment by Divineaspect** [comment]
porcelain has a clay + bonemeal recipie as well I believe. Which is unfortunately easy to get your hands on given bone blocks used in those skeletons in world.

I propose that the furnace require a block of charcoal in the middle, and any variety of bricks in the corners, including the dried mud bricks.

**Comment by belathus** [comment]
I think that we should build a gate around the wall of iron that requires the bronze age, but seeing as this discussion is mostly obsolete, lets move this to a new issue.
