### ISSUE TITLE
The Wall and Gate of Iron!

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#47]
Normal Methods of Processing Iron have been disabled, which ones do we want to allow?

- Diamond Hammers. It's the manual option for masochists.
- Immersive Engineering Rock Crusher to get iron chunks. Requires actual infrastructure.
- The Rockhounding Bloomery needs a more complex recipe, but blends 

are there any other processing methods we missed or might want to deliberately include.
Embers?

**Comment by Divineaspect** [comment]
Iron ore smelts into Slag Iron,  Slag Iron Ingots Pulverizes into 1 iron nugget

**Comment by belathus** [comment]
So, slag iron is no longer a thing.

Right now, you can process iron ore early on in the bronze age by crafting goethite and limonite into vanilla iron ore and hitting it with a crack hammer, then processing the iron dust in a smeltery. As of yesterday, I removed the ability to craft goethite and limonite into vanilla iron ore, so this is partially resolved; you can still find vanilla iron ore near rocky hives and in some Recurrent Complex structures (which we'll be adding more of according to issue #50). Outside of the vanilla iron ore, you cannot otherwise process iron ore with a crack hammer. You can, however, process the Rockhounding ores in a SAG mill, crusher, or bloomery.

You can still brute force your way through the iron age by exploration and finding lots of hives / ReComp structures, which I am okay with. By brute forcing your way through, you open up the option of processing iron with the SAG mill or crusher.

(I should point out that Actually Additions (the grinder), Blood Magic (alchemy?), Extra Utilities (crusher), and probably others that I am missing have ore processing. I admit that I am not including them in the list below, as I do not know how or even if I can edit them to be able to process the Rockhounding ores, which might be important for getting through the iron age. If we want to consider these, we're going to have to edit their recipes; that grinder from Actually Additions looks pretty cheap, costing flint, cobblestone, a couple crystals, and a few bits of iron.)

Lets see... IE's crusher is pretty expensive. It requires 8 steel fences, 10 steel scaffolding, 10 light engineering blocks, 9 hoppers, and 1 redstone engineering block. This has a total cost of (assuming I did my math right) 24 steel ingots, 109 iron ingots, 26 copper ingots, and 4 redstone dust. As such, you'll need to do a hell of a lot of exploring to collect enough iron for this, and already have steel processing to get out of the iron age. I don't think this is a viable path. We can make this a lot easier by reducing the cost of the light engineering blocks -- they account for 60 of the iron and 25 of the copper required. I don't know if we can eliminate the need for steel scaffolding and steel fences, and I'd rather not change the recipe for those. The hoppers can be made with tin, of course, which will replace 45 iron with 45 tin, though the tin seems to be hard to find right now (though easier to process).

The SAG mill takes, currently, 2 steel gears, 4 steel ingots, a diamond bore head, a machine chassis, and a piston. The chassis takes 4 steel bars, 4 steel ingots, and a basic capacitor. The bore head takes 8 steel ingots and a block of diamond. That comes to a total cost of 25.5 steel ingots, 9 diamonds, 1 iron, 2 copper, and 1 gold ingot. Even with the added requirement of gold and diamonds, I still think that this is by far the cheaper choice between the crusher and this.

The obvious solution to getting past the iron age is the bloomery.

**Comment by Divineaspect** [comment]
Esteemed Innovation's Smasher could work, it requires I think 2 iron and 2 redstone for the pistons.

**Comment by belathus** [comment]
I'm thinking of editing a lot of the recurrent complex pre-made structures that come with iron ore and mostly replacing it with goethite, copper, tin, and zinc to help break through the early tech.

**Comment by Divineaspect** [comment]
I think this is a transformer we can edit.

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by belathus** [comment]
We currently allow vanilla iron ore (and other ores that use oreIron oredict entry) smelt in a furnace. The ores that use oreIron include everything found in the nether, in the Misty World, and in the abyssalcraft dimensions. Should we continue allowing this, or should we use all Rockhounding ores and force them to get a bloomery?

**Comment by Alan19** [comment]
I'm OK with using XP to smelt

**Comment by belathus** [comment]
Closing this issue, as the things discussed here are way obsolete. We should create a new issue if we want more gates in the wall of iron.
