### ISSUE TITLE
Zombies breaking chests in roguelikes

### ISSUE THREAD

**Issue by Divineaspect** [belathus/Wanderlust-Renewed#78]

**Comment by belathus** [comment]
This shouldn't be an issue anymore, since we removed all chests from the blockbreaking list.

That being said, dungeon chests set up the way vanilla sets up dungeon chests (using the loot tags) should be immune to Special AI's behavior until you open them. Since Roguelike Dungeons doesn't follow this behavior, it is a problem unique to Roguelike Dungeon's chests. I think that the loot tags used in Recurrent Complex work for this regard, and I'd like to test this at some point.
